### ISSUE TITLE
Imitation - Copy error

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/vision-app#65]
Could you check if the imitation-copy button works well?

I just did linked these two artworks with an imitation/copy relationship, but the system suggests me the same match again. If I try to do the matching again I get an error ("failed to submit the form")

https://vision.artresearch.net/resource/?providera=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fsource%2FITatti&providerb=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fzeri%2Fsource%2FZeri&uri=https%3A%2F%2Fvision.artresearch.net%2Fresource%2FSimilarity%2F92524827026914589202834293

**Comment by sophisid** [comment]
You are right. We will look further this issue.

**Comment by sophisid** [comment]
The first problem has been solved. Now when the user makes a similarity of the types : Imitation/copy, Same negative, Study/sketch of , he is been redirected to a new similarity. 
And the similarity we have just done (Imitation/copy, Same negative, Study/sketch of) has been again to the reconsiliation stack, as before.
If we need to make an other implementation of these similarities (Imitation/copy, Same negative, Study/sketch of), as the Skip, wich we have marked them to be reviewed later, let me know.

**Comment by spykoulouris** [comment]
Sorry, I don't fully understand. You mean that we need to do again all matchings "Imitation/copy, Same negative, Study/sketch of" that were already done??

**Comment by sophisid** [comment]
You can now see the imitation/Copy here :
![image](https://user-images.githubusercontent.com/55842445/150362840-9c2d2b4b-0300-4db7-b9d6-59c809c3cf0a.png)

**Comment by spykoulouris** [comment]
I see. But why is this list empty in my dashboard? Is it possible to have back the imatation/copy I made that far?
That is one of the most tricky matchings to do and don't want to loose the work that has been done that far.

**Comment by spykoulouris** [comment]
Also the system still doesn't allow me to edit matchings that are under the "Marked for review" tab in the dashboard

**Comment by sophisid** [comment]
> Also the system still doesn't allow me to edit matchings that are under the "Marked for review" tab in the dashboard


As i see it allows the user to edit "Marked for review".

**Comment by sophisid** [comment]
> I see. But why is this list empty in my dashboard? Is it possible to have back the imatation/copy I made that far? That is one of the most tricky matchings to do and don't want to loose the work that has been done that far.

From the query you have reviewed some and they should appear.
![image](https://user-images.githubusercontent.com/55842445/150510142-5cd42a81-0d7b-44df-9b6c-b770504790c7.png)

I just noticed that your "Imitation/Copy" similarities are consider as skipped, which is not right.

**Comment by spykoulouris** [comment]
> > Also the system still doesn't allow me to edit matchings that are under the "Marked for review" tab in the dashboard
> 
> As i see it allows the user to edit "Marked for review".

It gives me an error when I try to do so

**Comment by spykoulouris** [comment]
> > I see. But why is this list empty in my dashboard? Is it possible to have back the imatation/copy I made that far? That is one of the most tricky matchings to do and don't want to loose the work that has been done that far.
> 
> From the query you have reviewed some and they should appear. ![image](https://user-images.githubusercontent.com/55842445/150510142-5cd42a81-0d7b-44df-9b6c-b770504790c7.png)
> 
> I just noticed that your "Imitation/Copy" similarities are consider as skipped, which is not right.

Now I can see 8 of them (yesterday there was zero results in this list). I'm not sure if before there were more

**Comment by sophisid** [comment]
Try to clean you browser cache. Maybe this is the problem, as if it was with the login.

**Comment by spykoulouris** [comment]
Do you have any updates on that? The imitation/copy tab in my dashboard has still 0 results, although I used this relationship several types.

I did clean my browser cache.

**Comment by sophisid** [comment]
Probably now you can see your imitation/copies

**Comment by mafragias** [comment]
Imitation/Copy of instance made by Spyros :

https://vision.artresearch.net/resource/Default:AllDashboard

![image](https://user-images.githubusercontent.com/23557768/158343093-2d3f0175-2f4a-40c4-b8ea-0d4621da700d.png)
